- README.md
View #6. It might be better to mount calibre-main/Calibre Library directly. Users with existing libraries will seamlessly mount it as before, and users without an existing one will more easily be able to follow these new instructions rather than the previously complex one of creating calibre-main/Calibre Library, bind only calibre-main/, and add metadata.db to calibre-main/Calibre Library.
> Directly bind calibre library to calibre-main/Calibre Library

- calibre-web-automator/books-to-process-detector.sh
- calibre-web-automator/new-book-detector.sh
Simple fix, just switching the inotify event from create to close_write. [Referenced this stackoverflow post](https://stackoverflow.com/questions/46542819/bash-script-inotifywait-wait-for-file-completely-written-before-proceding). Fixes #7 
I haven't tested it yet though but I'm fairly confident this will fix the problem. [Also edited the wiki page in the main calibre-web repo](https://github.com/janeczku/calibre-web/wiki/Automatically-import-new-books-(Linux))
> Fix auto importer from attempting to auto import half-transferred files

- calibre-web-automator/books-to-process-detector.sh
- calibre-web-automator/metadata-change-detector.sh
- calibre-web-automator/new-book-detector.sh
- calibre-web-automator/new-book-processor.py
3 Fixes added:
1. This fixes #14. Adding `-r` to `inotifywait` fixes not detecting folders within the ingest file. This bug was introduced by switching the inotify event from `create` to `close_write`, because `close_write` only gets triggered by files. Adding `-r` makes it get triggered by all folders recursively. The `--format` argument was needed to reorder the variables, because paths with spaces would mess up the variable ordering
2. d4b4d3f75d910c1585d8b8497de28aa91b3cae16 introduced a bug where folders wouldn't be deleted within ingest. Added `-d` arg to `find` for it to delete directories. Had to also add `-mindepth 1` to prevent the ingest folder itself getting deleted
3. Also fixes the 2nd half of #7
5.  When importing multiple files at once, each completed file will trigger …
> Fully fix auto import from attempting to import half-transferred files; Fix auto import not detecting folders; Fix ingest folders not getting deleted

- README.md
- calibre-web-automator/new-book-detector.sh
- calibre-web-automator/new-book-processor.py
As above, when moving a folder full a book files, it will not detect the files inside the moved folder. This PR adds code to the python file to loop through the detected folder
I also have fixed an issue that I have missed where new-book-detector would try adding the entire cwa-import dir into the calibre db, and I have forgotten to change it so it moves each individual file it detects. This fixed auto import potentially duplicating imports I think due to new-book-detector.sh adding the entire directory for every file added
Obviously, please test if this works for you. For me, it has fixed both moving and copying folders into auto-import. I have also updated the README to reflect these changes
> Fix folder recursion auto import issue when moving folders (not copy); Fix new-book-detector.sh adding entire directory 

- calibre-web-automator/constants.py
This one was a pretty simple change. Obviously because it's a docker image, the update button is unnecessary and can cause confusions and breakage. 
What I changed was the constants.py file in cps/constants.py in calibre-web. admin.html checks for this constant for whether it should show or not, so I set it to false.
I have not tested this, so be sure to do so. but feel like it should work given that calibre-web has already implemented logic to disable the button
References:
- [If statement for disabling updater button](https://github.com/janeczku/calibre-web/blob/f8adcbb69138a625d478b42808920bdbd3e4a7c6/cps/templates/admin.html#L237) 
- [Where the constant is set in admin.html (imported from constants.py)](https://github.com/janeczku/calibre-web/blob/f8adcbb69138a625d478b42808920bdbd3e4a7 …
> Disable updater in the admin settings

- root/app/calibre-web/cps/render_template.py
In case of a ratelimit github does not answer with the expected `tag_name` resulting in an error and therefore making the UI unusable.
I propose to make it so that if the expected `tag_name` key is not present replace it by the current version so that it does not result in an error and does not trigger update notification.
> fix: error when github does not respond with expected data.

- README.md
- build.sh
- docker-compose.yml.dev
I improved the table of contents linking by making them local rather than linking directly to crocodilestick/calibre-web-automated.
Also added syntax hightlighting to the code blocks in the README
> Add script to quickly build docker image and run container | Improve table of contents linking

- root/etc/s6-overlay/s6-rc.d/cwa-init-remove-locks/run
No comma needed, comma would be part of file name, i.e. not working
> Fix Lock Cleanup

- scripts/ingest_processor.py
When `kindle_epub_fixer` is `true`, we try to call the function in the same class `kindle_epub_fixer`, but since it got overwrite by init to be a bool, we fail with 
```
[ingest-processor]: No conversion needed for ebook.epub, importing now...
Traceback (most recent call last):
File "/app/calibre-web-automated/scripts/ingest_processor.py", line 257, in <module>
main()
File "/app/calibre-web-automated/scripts/ingest_processor.py", line 229, in main
nbp.add_book_to_library(filepath)
File "/app/calibre-web-automated/scripts/ingest_processor.py", line 167, in add_book_to_library
self.kindle_epub_fixer(book_path)
```
This PR renames the bool to avoid the issue
> [bug] kindle_epub_fixer used as function name and as boolean

- root/app/calibre-web/cps/metadata_provider/ibdb.py
https://ibdb.dev/ is a book metadata service I set up, backed by https://isbndb.com/
> add ibdb.dev as a metadata provider

- scripts/ingest_processor.py
This is a fix for #238.
The underlying issue was that the `tmp_conversion_dir` defined as `/config/.cwa_conversion_tmp` in `dirs.json` did not exist prior to invocation of the ingest-processor.
EDIT: fixed the bug issue reference that I had previously wrongly indicated was #236. Sorry.
> Minor fix to ingest-processor to create the tmp_conversion_dir if it does not already exist

- Dockerfile
- Dockerfile_calibre_not_included
Fixes #267 
Additionally allows specifying kepubify version in args.
Tested on RPI, it now converts fine:
> Fix incorrect kepubify package for arm64

- scripts/ingest_processor.py
Check if imported file was in ingest_folder or a subdirectory, if a subdirectory then all empty directories are removed. This prevents folders such as .stfolder for SyncThing and other non import directories from being removed.
> Narrows scope of ingest delete function

- scripts/convert_library.py
When converting to **.kepub** only the filename of the source was being passed, not the full path. This resulted in an error message like: `[Errno 2] No such file or directory: '<example ebook>.epub'`.
The `convert_library.py` script was updated to pass the full path.
This fixes bug #219.
> Fix: Kepub conversion not being passed the full path of the source file.

- .gitattributes
- Dockerfile
- Add `binutils` to install `strip` for calibre-included Dockerfile.
- strip `libQt6*.so` files of the `ABI` tag so that they can work with older kernels (harmless for newer kernels).
- These libraries appear to still contain fallbacks for any missing syscalls that calibre might use.
- add .gitattributes to enforce LF checkout on `.sh` files (useful for those who build on windows)
> Fix for older kernels (E.G. synology) - Remove the ABI tag from the extracted libQt6* files

- root/app/calibre-web/cps/shelf.py
- root/app/calibre-web/cps/static/js/table.js
- root/app/calibre-web/cps/templates/book_table.html
This commit introduces a new feature allowing you to add multiple books selected from the book list page to a specified shelf.
Key changes include:
-   **Backend (`shelf.py`):**
-   Added a new POST endpoint `/shelf/add_selected_to_shelf`.
-   This endpoint accepts a shelf ID and a list of book IDs in a JSON payload.
-   It performs permission checks, validates book and shelf existence, and checks for duplicates before adding books to the shelf.
-   Returns JSON responses indicating success (with count of books added) or errors (with specific messages).
-   **Frontend Template (`book_table.html`):**
-   Added an "Add to Shelf" button to the bulk action controls on the book list page.
-   Implemented a Bootstrap modal dialog for you to select the target shelf from your accessible shelves. …
> feat: Add 'Add Selected Books to Shelf' functionality

- root/app/calibre-web/cps/kobo.py
Add support for native notebook syncing. This solution was proposed and proven effective following this thread. Allows using Calibre-Web-Automated sync while still being able to backup notebooks to Kobo. https://github.com/janeczku/calibre-web/issues/2849#issuecomment-2613986184
> Solve sync failing by supporting POST in route for notebooks

- scripts/ingest_processor.py
Remove the . (dot) from the check, since ingest_ignored_formats gives a list whitout . (dots)
> Use replace to get the suffix only (no .)

- root/app/calibre-web/cps/cwa_functions.py
- root/app/calibre-web/cps/templates/cwa_settings.html
- scripts/cwa_schema.sql
- scripts/ingest_processor.py
This is an attempt to address #340 #334 #208 as well as my own desire to overwrite duplicate books on import by adding a new setting that matches the three possible values of [calibredb's `--automerge` parameter](https://manual.calibre-ebook.com/generated/en/calibredb.html#cmdoption-calibredb-add-automerge). This replaces the hardcoded `new_record` value in [`add_book_to_library`](scripts/ingest_processor.py). The default value matches the previous behaviour.
I have done my best to keep this fairly minimal and to match any existing patterns where I was able to identify them. Please let me know your thoughts on a feature like this in general as well as this PR.
> Add configurable setting for ingest automerge parameter 

- cps/templates/kosync_plugin.html
Remove `/kosync` from the CWA KOSync plugin page because the plugin is automatically appending it to the url. See #463
> bug issue #463. kosync plugin url

- cps/templates/kosync_plugin.html
- cps/translations/de/LC_MESSAGES/messages.po
I removed the reference to iOS as koreader is not availible there (and no reader kompatible to kosync to my knowledge)
> Update kosync_plugin.html to removed iOS reference

- README.md
- cps/__init__.py
- cps/constants.py
- cps/cwa_functions.py
- docker-compose.yml
- scripts/convert_library.py
- scripts/ingest_processor.py
Added acsm to the various file format lists (and the mimetypes list) so CWA accepts them for converts, ingestion, and uploads. Also, I found that calibre's customize.py.json also needs to be copied to get a fresh install working with plugins, so I added notes to the readme and docker-compose files.
> Add support for uploading, ingesting, and converting .acsm and include additional plugin documentation

- cps/web.py
Updated the health check function to use os.path.join for constructing the database path. 
This resolves the health check always failing due to incorrect path handling.
> Fix health check database path concatenation

- scripts/ingest_processor.py
The logic does a `Path(filename).suffix.replace('.', '')` which then compares to the ingest_ignored_formats with a dot, meaning it never matches.
> Remove `.` in ingest_ignored_formats for partial download

- cps/services/hardcover.py
https://github.com/crocodilestick/Calibre-Web-Automated/issues/509
By changing 'is not' to '!=' so syncing reading progress is actually executed instead of the error we're seeing in the logs:
> WARN {py.warnings:109} /app/calibre-web-automated/cps/services/hardcover.py:110: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if len(ids) is not 0:<
> Should fix issue: 509

- cps/helper.py
It needed for litres metata provider #550 , but i think i may be usefull for others..
some examples:
- https://www.litres.ru/pub/c/cover/70920901.jpg
- https://www.litres.ru/pub/c/cover/69932440.jpg
> Add supporting for cover content types with ',' separator

- cps/uploader.py
Not sure what it looks like in `xmp_info`, and it seems like all my PDFs have it in `doc_info`
> feat: read createdate from pdf and add as pubdate
